version: '3.8'

services:
  video_monitor:
    build:
      context: .
      dockerfile: Dockerfile.simple
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///video_monitoring.db
      - PYTHONUNBUFFERED=1
    volumes:
      - ./videos:/app/videos
      - ./clips:/app/clips
      - ./logs:/app/logs
      - ./video_monitoring.db:/app/video_monitoring.db
    networks:
      - video_network
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - video_monitor
    networks:
      - video_network
    restart: unless-stopped

volumes:
  video_data:

networks:
  video_network:
    driver: bridge